# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: to_bool 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "to_bool"
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jon Frisby"]
  s.date = "2016-09-23"
  s.description = "Add a to_bool method to all objects that Does What You Mean."
  s.email = "jfrisby@mrjoy.com"
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".pelusa.yml",
    "CHANGELOG.md",
    "LICENSE",
    "README.md",
    "lib/test/simplecov.rb",
    "lib/to_bool.rb",
    "to_bool.gemspec"
  ]
  s.homepage = "http://github.com/MrJoy/to_bool"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Add a to_bool method to all objects that Does What You Mean."
end

