# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "to_bool"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jon Frisby"]
  s.date = "2012-08-15"
  s.description = "Add a to_bool method to all objects that Does What You Mean."
  s.email = "jfrisby@mrjoy.com"
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".pelusa.yml",
    "CHANGELOG.md",
    "LICENSE",
    "README.md",
    "lib/test/simplecov.rb",
    "lib/to_bool.rb"
  ]
  s.homepage = "http://github.com/MrJoy/to_bool"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Add a to_bool method to all objects that Does What You Mean."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

